version: '3'

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - service_network
    restart: unless-stopped

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - service_network
    restart: unless-stopped

  elasticsearch:
    image: elasticsearch:8.6.2
    container_name: "elasticsearch"
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - service_network
    healthcheck:
      test: [ "curl", "-f", "'http://elasticsearch:9200/_cluster/health?wait_for_status=yellow&timeout=5s'" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  maildev:
    image: maildev/maildev
    container_name: maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - service_network
    restart: unless-stopped

  javastuff:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_ELASTICSEARCH_URIS=elasticsearch:9200
    depends_on:
      - kafka
      - elasticsearch
      - maildev
    ports:
      - "8080:8080"
    networks:
      - service_network
    restart: unless-stopped

networks:
  service_network:
    driver: bridge
